/**
* Tucuxi TDM server
* This is the Tucuxi TDM server.
*
* OpenAPI spec version: 1.0.0
* Contact: nadir.benallal@heig-vd.ch
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
/*
 * DrugsApi.h
 *
 * 
 */

#ifndef TUCUXI_SERVER_DRUGS_API_H_
#define TUCUXI_SERVER_DRUGS_API_H_


#include <pistache/endpoint.h>
#include <pistache/http.h>
#include <pistache/router.h>
#include <pistache/http_headers.h>

#include "../communication/query.h"
#include "../communication/xmlreader.h"

#include <string>

namespace Tucuxi {
namespace Server {
namespace API {

class  DrugsApi {
public:
    DrugsApi(std::shared_ptr<Pistache::Http::Endpoint> _pEndpoint, std::shared_ptr<Pistache::Rest::Router> _pRouter);
    virtual ~DrugsApi() {}

    void setupRoutes();

private:
    void add_drug_handler(const Pistache::Rest::Request& _request, Pistache::Http::ResponseWriter _response);
    void delete_drug_handler(const Pistache::Rest::Request& _request, Pistache::Http::ResponseWriter _response);
    void edit_drug_handler(const Pistache::Rest::Request& _request, Pistache::Http::ResponseWriter _response);
    void get_drug_handler(const Pistache::Rest::Request& _request, Pistache::Http::ResponseWriter _response);
    void list_drugs_handler(const Pistache::Rest::Request& _request, Pistache::Http::ResponseWriter _response);
    void drugs_api_default_handler(const Pistache::Rest::Request& _request, Pistache::Http::ResponseWriter _response);


    /// <summary>
    /// Adds a new drug.
    /// </summary>
    /// <remarks>
    /// Adds a new drug to the list of the ones managed by the server.
    /// </remarks>
    /// <param name="_query">XML desciption of a drug.</param>
    virtual void add_drug(const Query& _query, Pistache::Http::ResponseWriter& _response) = 0;

    /// <summary>
    /// Delete the desired drug.
    /// </summary>
    /// <remarks>
    /// Delete the drug desciption file referenced by the drug identifier.
    /// </remarks>
    /// <param name="_drugID">Unique identifier of the drug.</param>
    virtual void delete_drug(const std::string& _drugID, Pistache::Http::ResponseWriter& _response) = 0;

    /// <summary>
    /// Edit the desired drug
    /// </summary>
    /// <remarks>
    /// Changes the XML drug desciption file with the one sent.
    /// </remarks>
    /// <param name="_drugID">Unique identifier of the drug.</param>
    /// <param name="_query">New XML drug desciption file.</param>
    virtual void edit_drug(const std::string& _drugID, const Query& _query, Pistache::Http::ResponseWriter& _response) = 0;

    /// <summary>
    /// Get the desired drug
    /// </summary>
    /// <remarks>
    /// Returns the desired drug XML header node.
    /// </remarks>
    /// <param name="_drugID">Unique identifier of the drug.</param>
    virtual void get_drug(const std::string& _drugID, Pistache::Http::ResponseWriter& _response) = 0;

    /// <summary>
    /// Returns the list of all supported drugs
    /// </summary>
    /// <remarks>
    /// Returns the header node of each XML drug desciption file that the server is able to manage.
    /// </remarks>
    virtual void list_drugs(Pistache::Http::ResponseWriter& _response) = 0;

public:
    const std::string base = "/";

private:
    std::shared_ptr<Pistache::Http::Endpoint> m_httpEndpoint;
    std::shared_ptr<Pistache::Rest::Router> m_router;

};

} // namespace API
} // namespace Server
} // namespace Tucuxi

#endif /* TUCUXI_SERVER_DRUGS_API_H_ */

