/**
* Hello World C++ Pistache server
* This is a Hello World server.
*
* OpenAPI spec version: 1.0.0
* Contact: nadir.benallal@heig-vd.ch
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
/*
 * HelloApi.h
 *
 * 
 */

#ifndef TUCUXI_SERVER_HELLO_API_H_
#define TUCUXI_SERVER_HELLO_API_H_


#include <pistache/endpoint.h>
#include <pistache/http.h>
#include <pistache/router.h>
#include <pistache/http_headers.h>

#include <string>

#include "../communication/query.h"
#include "../communication/xmlreader.h"
#include "rapidxml.hpp"

namespace Tucuxi {
namespace Server {
namespace API {

class  HelloApi {
public:
    HelloApi(std::shared_ptr<Pistache::Http::Endpoint> _pEndpoint, std::shared_ptr<Pistache::Rest::Router> _pRouter);
    virtual ~HelloApi() {}

    void setupRoutes();

private:
    void hello_world_handler(const Pistache::Rest::Request& _request, Pistache::Http::ResponseWriter _response);
    void test_query_handler(const Pistache::Rest::Request& _request, Pistache::Http::ResponseWriter _response);
    void hello_api_default_handler(const Pistache::Rest::Request& _request, Pistache::Http::ResponseWriter _response);

    /// <summary>
    /// Returns \&quot;Hello World!\&quot;
    /// </summary>
    /// <remarks>
    /// Returns the string \&quot;Hello World!\&quot;
    /// </remarks>
    virtual void hello_world(Pistache::Http::ResponseWriter& _response) = 0;

    /// <summary>
    /// Send a query for a test
    /// </summary>
    /// <remarks>
    /// Send query in XML format to see if it&#39;s processed correctly.
    /// </remarks>
    /// <param name="_query">Query object containing the list of requests</param>
    virtual void test_query(const Query& _query, Pistache::Http::ResponseWriter& _response) = 0;

public:
    const std::string base = "/";

private:
    std::shared_ptr<Pistache::Http::Endpoint> m_httpEndpoint;
    std::shared_ptr<Pistache::Rest::Router> m_router;

};

} // namespace API
} // namespace Server
} // namespace Tucuxi

#endif /* TUCUXI_SERVER_HELLO_API_H_ */

