var searchData=
[
  ['xml_0',['XML',['../namespace_tucuxi_1_1_xpert.html#ab27e010943a928c01ea824d5cd4491dda3501bb093d363810b671059b9cfed3f8',1,'Tucuxi::Xpert']]],
  ['xpertquerydata_1',['XpertQueryData',['../class_tucuxi_1_1_xpert_1_1_xpert_query_data.html',1,'Tucuxi::Xpert::XpertQueryData'],['../class_tucuxi_1_1_xpert_1_1_xpert_query_data.html#acbfc67eba9fe4bf24dc7b1aa1c5458dd',1,'Tucuxi::Xpert::XpertQueryData::XpertQueryData(const XpertQueryData &amp;_other)=delete'],['../class_tucuxi_1_1_xpert_1_1_xpert_query_data.html#ae6b8ee88c94587353c6a9d1fd59e7ae9',1,'Tucuxi::Xpert::XpertQueryData::XpertQueryData(const std::string &amp;_queryId, const std::string &amp;_clientId, const Common::DateTime &amp;_queryDate, const std::string &amp;_language, std::unique_ptr&lt; AdminData &gt; _admin, std::unique_ptr&lt; Query::DrugTreatmentData &gt; _parameters, std::vector&lt; std::unique_ptr&lt; Query::RequestData &gt; &gt; &amp;_requests, std::vector&lt; std::unique_ptr&lt; XpertRequestData &gt; &gt; &amp;_xpertRequests)']]],
  ['xpertquerydata_2ecpp_2',['xpertquerydata.cpp',['../xpertquerydata_8cpp.html',1,'']]],
  ['xpertquerydata_2eh_3',['xpertquerydata.h',['../xpertquerydata_8h.html',1,'']]],
  ['xpertqueryimport_4',['XpertQueryImport',['../class_tucuxi_1_1_xpert_1_1_xpert_query_import.html',1,'Tucuxi::Xpert::XpertQueryImport'],['../class_tucuxi_1_1_xpert_1_1_xpert_query_import.html#a0df6e4b004501463a0342ca117a710cc',1,'Tucuxi::Xpert::XpertQueryImport::XpertQueryImport()']]],
  ['xpertqueryimport_2ecpp_5',['xpertqueryimport.cpp',['../xpertqueryimport_8cpp.html',1,'']]],
  ['xpertqueryimport_2eh_6',['xpertqueryimport.h',['../xpertqueryimport_8h.html',1,'']]],
  ['xpertqueryresult_7',['XpertQueryResult',['../class_tucuxi_1_1_xpert_1_1_xpert_query_result.html',1,'Tucuxi::Xpert::XpertQueryResult'],['../class_tucuxi_1_1_xpert_1_1_xpert_query_result.html#a8e052009a7d2dffa76307160cd415753',1,'Tucuxi::Xpert::XpertQueryResult::XpertQueryResult(const XpertQueryResult &amp;_other)=delete'],['../class_tucuxi_1_1_xpert_1_1_xpert_query_result.html#a8c8f3f739f4f04ad368c79e4edfe2845',1,'Tucuxi::Xpert::XpertQueryResult::XpertQueryResult(std::unique_ptr&lt; XpertQueryData &gt; _xpertQuery, const std::string &amp;_outputPath)']]],
  ['xpertqueryresult_2ecpp_8',['xpertqueryresult.cpp',['../xpertqueryresult_8cpp.html',1,'']]],
  ['xpertqueryresult_2eh_9',['xpertqueryresult.h',['../xpertqueryresult_8h.html',1,'']]],
  ['xpertquerytocoreextractor_10',['XpertQueryToCoreExtractor',['../class_tucuxi_1_1_xpert_1_1_xpert_query_to_core_extractor.html',1,'Tucuxi::Xpert']]],
  ['xpertquerytocoreextractor_2ecpp_11',['xpertquerytocoreextractor.cpp',['../xpertquerytocoreextractor_8cpp.html',1,'']]],
  ['xpertquerytocoreextractor_2eh_12',['xpertquerytocoreextractor.h',['../xpertquerytocoreextractor_8h.html',1,'']]],
  ['xpertrequestdata_13',['XpertRequestData',['../class_tucuxi_1_1_xpert_1_1_xpert_request_data.html',1,'Tucuxi::Xpert::XpertRequestData'],['../class_tucuxi_1_1_xpert_1_1_xpert_request_data.html#aec806ec24d3f43ee166b52da186913ec',1,'Tucuxi::Xpert::XpertRequestData::XpertRequestData()']]],
  ['xpertrequestdata_2ecpp_14',['xpertrequestdata.cpp',['../xpertrequestdata_8cpp.html',1,'']]],
  ['xpertrequestdata_2eh_15',['xpertrequestdata.h',['../xpertrequestdata_8h.html',1,'']]],
  ['xpertrequestresult_16',['XpertRequestResult',['../class_tucuxi_1_1_xpert_1_1_xpert_request_result.html',1,'Tucuxi::Xpert::XpertRequestResult'],['../class_tucuxi_1_1_xpert_1_1_xpert_request_result.html#aa182b5e3b28b424011bec2a720b56323',1,'Tucuxi::Xpert::XpertRequestResult::XpertRequestResult()']]],
  ['xpertrequestresult_2ecpp_17',['xpertrequestresult.cpp',['../xpertrequestresult_8cpp.html',1,'']]],
  ['xpertrequestresult_2eh_18',['xpertrequestresult.h',['../xpertrequestresult_8h.html',1,'']]],
  ['xpertrequestresulthtmlexport_19',['XpertRequestResultHtmlExport',['../class_tucuxi_1_1_xpert_1_1_xpert_request_result_html_export.html',1,'Tucuxi::Xpert']]],
  ['xpertrequestresulthtmlexport_2ecpp_20',['xpertrequestresulthtmlexport.cpp',['../xpertrequestresulthtmlexport_8cpp.html',1,'']]],
  ['xpertrequestresulthtmlexport_2eh_21',['xpertrequestresulthtmlexport.h',['../xpertrequestresulthtmlexport_8h.html',1,'']]],
  ['xpertrequestresultpdfexport_22',['XpertRequestResultPdfExport',['../class_tucuxi_1_1_xpert_1_1_xpert_request_result_pdf_export.html',1,'Tucuxi::Xpert::XpertRequestResultPdfExport'],['../class_tucuxi_1_1_xpert_1_1_xpert_request_result_pdf_export.html#a06c91558d545b579957c9a4d49cd0e00',1,'Tucuxi::Xpert::XpertRequestResultPdfExport::XpertRequestResultPdfExport()']]],
  ['xpertrequestresultpdfexport_2ecpp_23',['xpertrequestresultpdfexport.cpp',['../xpertrequestresultpdfexport_8cpp.html',1,'']]],
  ['xpertrequestresultpdfexport_2eh_24',['xpertrequestresultpdfexport.h',['../xpertrequestresultpdfexport_8h.html',1,'']]],
  ['xpertrequestresultxmlexport_25',['XpertRequestResultXmlExport',['../class_tucuxi_1_1_xpert_1_1_xpert_request_result_xml_export.html',1,'Tucuxi::Xpert']]],
  ['xpertrequestresultxmlexport_2ecpp_26',['xpertrequestresultxmlexport.cpp',['../xpertrequestresultxmlexport_8cpp.html',1,'']]],
  ['xpertrequestresultxmlexport_2eh_27',['xpertrequestresultxmlexport.h',['../xpertrequestresultxmlexport_8h.html',1,'']]],
  ['xpertutils_2ecpp_28',['xpertutils.cpp',['../xpertutils_8cpp.html',1,'']]],
  ['xpertutils_2eh_29',['xpertutils.h',['../xpertutils_8h.html',1,'']]]
];
