/**
* Tucuxi TDM server
* This is the Tucuxi TDM server.
*
* OpenAPI spec version: 1.0.0
* Contact: nadir.benallal@heig-vd.ch
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/

/*
* ComputationApiImpl.h
*
* 
*/

#ifndef TUCUXI_SERVER_COMPUTATION_API_IMPL_H_
#define TUCUXI_SERVER_COMPUTATION_API_IMPL_H_


#include <pistache/endpoint.h>
#include <pistache/http.h>
#include <pistache/router.h>
#include <memory>

#include "../api/ComputationApi.h"

#include "../communication/query.h"
#include "../predictioncomputer.h"
#include "../adjustmentcomputer.h"
#include "../firstdosagecomputer.h"
#include "../communication/apiresponsewriter.h"

namespace Tucuxi {
namespace Server {
namespace API {

class ComputationApiImpl : public Tucuxi::Server::API::ComputationApi {
public:
    ComputationApiImpl(std::shared_ptr<Pistache::Http::Endpoint> _pEndpoint, std::shared_ptr<Pistache::Rest::Router> _pRouter);
    ~ComputationApiImpl() { }

    void compute_requests(const Query& _query, Pistache::Http::ResponseWriter& _response);

};

} // namespace API
} // namespace Server
} // namespace Tucuxi



#endif /* TUCUXI_SERVER_COMPUTATION_API_IMPL_H_ */
