/**
* Tucuxi TDM server
* This is the Tucuxi TDM server.
*
* OpenAPI spec version: 1.0.0
* Contact: nadir.benallal@heig-vd.ch
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/

#include "DrugsApiImpl.h"

namespace Tucuxi {
namespace Server {
namespace API {

DrugsApiImpl::DrugsApiImpl(std::shared_ptr<Pistache::Http::Endpoint> _pEndpoint, std::shared_ptr<Pistache::Rest::Router> _pRouter)
    : DrugsApi(_pEndpoint, _pRouter)
    { }

void DrugsApiImpl::add_drug(const Query& _query, Pistache::Http::ResponseWriter& _response) {
    std::string mandatorFirstName = _query.getpAdmin()
                                    .getpMandator()
                                    .getpPerson()
                                    .getFirstName();
    std::string mandatorLastName = _query.getpAdmin()
                                    .getpMandator()
                                    .getpPerson()
                                    .getLastName();

    std::string text = "This request was sent by mandator: " +
            mandatorFirstName + " " + mandatorLastName +
            " on the drugs endpoint.";

    _response.send(Pistache::Http::Code::Ok, text);
}

void DrugsApiImpl::delete_drug(const std::string& _drugID, Pistache::Http::ResponseWriter& _response) {
    std::string text = "Request received on the drugs endpoint with id: " + _drugID;
    _response.send(Pistache::Http::Code::Ok, text);
}

void DrugsApiImpl::edit_drug(const std::string& _drugID, const Query& _query, Pistache::Http::ResponseWriter& _response) {
    std::string mandatorFirstName = _query.getpAdmin()
                                    .getpMandator()
                                    .getpPerson()
                                    .getFirstName();
    std::string mandatorLastName = _query.getpAdmin()
                                    .getpMandator()
                                    .getpPerson()
                                    .getLastName();

    std::string text = "This request was sent by mandator: " +
            mandatorFirstName + " " + mandatorLastName +
            " on the drugs endpoint with id: " + _drugID;

    _response.send(Pistache::Http::Code::Ok, text);
}

void DrugsApiImpl::get_drug(const std::string& _drugID, Pistache::Http::ResponseWriter& _response) {
    std::string text = "Request received on the drugs endpoint with id: " + _drugID;
    _response.send(Pistache::Http::Code::Ok, text);
}

void DrugsApiImpl::list_drugs(Pistache::Http::ResponseWriter& _response) {
    std::string text = "Request received on the drugs endpoint.";
    _response.send(Pistache::Http::Code::Ok, text);
}

} // namespace API
} // namespace Server
} // namespace Tucuxi

