/**
* Tucuxi TDM server
* This is the Tucuxi TDM server.
*
* OpenAPI spec version: 1.0.0
* Contact: nadir.benallal@heig-vd.ch
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/

/*
* DrugsApiImpl.h
*
* 
*/

#ifndef TUCUXI_SERVER_DRUGS_API_IMPL_H_
#define TUCUXI_SERVER_DRUGS_API_IMPL_H_


#include <pistache/endpoint.h>
#include <pistache/http.h>
#include <pistache/router.h>
#include <memory>

#include "../api/DrugsApi.h"

#include "../communication/query.h"
#include <string>

namespace Tucuxi {
namespace Server {
namespace API {

class DrugsApiImpl : public Tucuxi::Server::API::DrugsApi {
public:
    DrugsApiImpl(std::shared_ptr<Pistache::Http::Endpoint> _pEndpoint, std::shared_ptr<Pistache::Rest::Router> _pRouter);
    ~DrugsApiImpl() { }

    void add_drug(const Query& _query, Pistache::Http::ResponseWriter& _response);
    void delete_drug(const std::string& _drugID, Pistache::Http::ResponseWriter& _response);
    void edit_drug(const std::string& _drugID, const Query& _query, Pistache::Http::ResponseWriter& _response);
    void get_drug(const std::string& _drugID, Pistache::Http::ResponseWriter& _response);
    void list_drugs(Pistache::Http::ResponseWriter& _response);

};

} // namespace API
} // namespace Server
} // namespace Tucuxi



#endif /* TUCUXI_SERVER_DRUGS_API_IMPL_H_ */
