/**
* Hello World C++ Pistache server
* This is a Hello World server.
*
* OpenAPI spec version: 1.0.0
* Contact: nadir.benallal@heig-vd.ch
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/

/*
* HelloApiImpl.h
*
* 
*/

#ifndef TUCUXI_SERVER_HELLO_API_IMPL_H_
#define TUCUXI_SERVER_HELLO_API_IMPL_H_


#include <pistache/endpoint.h>
#include <pistache/http.h>
#include <pistache/router.h>
#include <memory>

#include "../api/HelloApi.h"

#include <string>

namespace Tucuxi {
namespace Server {
namespace API {

class HelloApiImpl : public HelloApi {
public:
    HelloApiImpl(std::shared_ptr<Pistache::Http::Endpoint> _pEndpoint, std::shared_ptr<Pistache::Rest::Router> _pRouter);
    ~HelloApiImpl() { }

    void hello_world(Pistache::Http::ResponseWriter& _response);
    void test_query(const Query& _query, Pistache::Http::ResponseWriter& _response);

};

} // namespace API
} // namespace Server
} // namespace Tucuxi



#endif /* TUCUXI_SERVER_HELLO_API_IMPL_H_ */
