/**
* Hello World C++ Pistache server
* This is a Hello World server.
*
* OpenAPI spec version: 1.0.0
* Contact: nadir.benallal@heig-vd.ch
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/

#include "HelloApiImpl.h"

namespace Tucuxi {
namespace Server {
namespace API {

HelloApiImpl::HelloApiImpl(std::shared_ptr<Pistache::Http::Endpoint> _pEndpoint, std::shared_ptr<Pistache::Rest::Router> _pRouter)
    : HelloApi(_pEndpoint, _pRouter)
    {}

void HelloApiImpl::hello_world(Pistache::Http::ResponseWriter& _response) {
    _response.send(Pistache::Http::Code::Ok, "Hello World!\n");
}

void HelloApiImpl::test_query(const Query& _query, Pistache::Http::ResponseWriter& _response) {

    std::string text = "Just received request with queryID: " + _query.getQueryID() + ".";
    _response.send(Pistache::Http::Code::Ok, text);
}

} // namespace API
} // namespace Server
} // namespace Tucuxi

